# Project identity - lowercase and underscores only
name: 'credit_card_analytics'
version: '1.0.0'

# Links to connection profile in profiles.yml
profile: 'credit_card_analytics'

# Directory structure - where dbt searches for project components
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Cleanup targets for dbt clean command
clean-targets:
  - "target"
  - "dbt_packages"

# Model materialization strategy
models:
  credit_card_analytics:
    +materialized: view         # Project-wide default for all models
    
    staging:
      +materialized: view       # Explicit staging config for future customization
