version: 2

models:
  - name: stg_raw_transactions
    description: "Cleaned and standardized transaction data from raw source"
    columns:
      - name: transaction_id
        description: "Unique transaction identifier"
        data_tests:
          - not_null

      - name: transaction_timestamp
        description: "Absolute timestamp anchored to 2013-09-01 baseline"

      - name: time_seconds
        description: "Relative time in seconds from first transaction (for velocity calculations)"

      - name: amount
        description: "Transaction amount in currency units"
        data_tests:
          - not_null

      - name: is_fraud
        description: "Fraud indicator (1=fraud, 0=legitimate)"
        data_tests:
          - not_null
          - accepted_values:
              values: [0, 1]
              quote: false
