version: 2

models:
  - name: int_transaction_features
    description: "Intermediate features derived from staging transactions for analytics"
    columns:
      - name: transaction_id
        description: "Unique transaction identifier"
        data_tests:
          - unique
          - not_null
      
      - name: transaction_timestamp
        description: "Absolute timestamp"
        data_tests:
          - not_null
      
      - name: time_seconds
        description: "Relative time in seconds from first transaction (passed through for velocity calculations)"

      - name: transaction_date
        description: "Date extracted from timestamp (for daily aggregations)"
        data_tests:
          - not_null
      
      - name: hour_of_day
        description: "Hour of day (0-23) for hourly pattern analysis"
        data_tests:
          - not_null
      
      - name: day_of_week
        description: "Day of week (1=Sunday, 7=Saturday)"
      
      - name: amount
        description: "Transaction amount in currency units"
        data_tests:
          - not_null
      
      - name: amount_z
        description: "Z-score of transaction amount (measures standard deviations from mean, values >3 indicate outliers)"
      
      - name: amount_log
        description: "Natural log of (amount + 1) to compress range for ML models"
      
      - name: is_fraud
        description: "Fraud indicator: 1=fraudulent, 0=legitimate"
        data_tests:
          - not_null
