version: 2

models:
  - name: fraud_risk_scores
    description: "Partitioned and clustered gold mart for fraud analytics and reporting"
    columns:
      - name: transaction_id
        description: "Unique transaction identifier"
        data_tests:
          - unique
          - not_null
          
      - name: transaction_date
        description: "Date for partitioning (enables efficient date-range queries)"
        data_tests:
          - not_null
          
      - name: amount
        description: "Transaction amount in euros"
        data_tests:
          - not_null
          
      - name: is_fraud
        description: "Fraud indicator: 1=fraudulent, 0=legitimate"
        data_tests:
          - not_null
          
      - name: amount_risk_category
        description: "Risk category based on z-score: High/Medium/Low Risk"
        data_tests:
          - not_null
